---
title: "TOC take 2"
author: "Tim Lamour"
date: "11/22/2020"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(lubridate)
```



```{r}
excel_sheets("~/Desktop/Github/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx")

metadata <- read_excel("~/Desktop/Github/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Metadata")

data <- read_excel("~/Desktop/Github/144l_students/Input_Data/week4/144L_2018_Exp_TOC.xlsx", sheet = "Data")
```

```{r}
joined <- left_join(metadata, data)

toc <- joined %>%
  mutate(Datetime = ymd_hm(Datetime)) %>%
  group_by(Experiment, Bottle) %>%
  mutate(interv = interval(first(Datetime), Datetime),
         interv = as.duration(interv),
         hours = as.numeric(interv)/3600,
         days = hours/24) %>%
  ungroup() %>%
  rename(sd_TOC = TOC_sd,
         sd_PTOC = PTOC_sd) %>%
  select(Experiment:Datetime, hours, days, everything(), -c(TOC_Sample:DNA_Sample), interv)


```

```{r}
glimpse(toc)
```
```{r}
bc <- read_rds("~/Desktop/Github/144l_students/Output_data/EEMB144L_Exp_processed_DOC.rds")

merge <- left_join(toc, bc) %>%
  select(Experiment:sd_PTOC, cells:diff_ln_cells, bc, ave_bc, sd_bc, everything(), -c(TOC_Sample:Cell_Sample)) %>%
  group_by(Experiment, Treatment, Bottle) %>%
  fill(exp_start:sd_lag) %>%
  ungroup()

subset <- merge %>%
  select(Experiment, Treatment, Bottle, days, PTOC, bc)
```

```{r}
glimpse(merge) 

```


```{r}
library(zoo)
```
```{r}
to_interpolate <- merge %>%
  select(Experiment, Bottle, Timepoint, days, PTOC, bc) %>%
  group_by(Experiment, Bottle)

list <- to_interpolate %>%
  group_split()

keys <- to_interpolate %>%
  group_keys() %>%
  mutate(key = paste(Experiment, Bottle))

names(list) <- keys$key
```

```{r}
interp.func <- function(x) {
  y <- zoo(x, order.by = x$days) 
  interp_toc <- round(as.numeric(na.approx(y$PTOC, na.rm = F)), 1)
  interp_bc <- round(as.numeric(na.approx(y$bc, na.rm = F)), 1)
  z <- cbind(y, interp_toc, interp_bc)
  as_tibble(z)
}
```

```{r}
interpolated <- lapply(list, interp.func) %>%
  plyr::ldply(., as.data.frame) %>%
  select(-c(.id, PTOC, bc, days)) %>%
  mutate_at(vars(Timepoint:interp_bc), as.numeric) %>%
  left_join(merge, .)
```
```{r}
glimpse(interpolated)
```

```{r}
doc <- interpolated %>%
  mutate(doc = interp_toc - interp_bc) %>%
  group_by(Experiment, Bottle) %>%
  mutate(bioav_doc = (first(doc) - last(na.omit(doc))) / first(doc), 
         doc_exp_end = ifelse(Timepoint == exp_end, doc, NA), 
         delta_doc = first(doc) - doc_exp_end, 
         tdelta_doc = first(doc) - last(na.omit(doc)), 
         bge = ifelse(delta_doc > 1.5, delta_bc/delta_doc, NA)) %>%
  fill(doc_exp_end:bge, .direction = "downup") %>%
  ungroup()
```

```{r}
averages <- doc %>%
  group_by(Experiment, Treatment, Timepoint) %>%
  mutate(ave_toc = mean(PTOC), 
         sd_toc = sd(PTOC)) %>%
  ungroup() %>%
  group_by(Experiment, Treatment) %>%
  mutate(ave_bioav_doc = mean(bioav_doc), 
         sd_bioav_doc = sd(bioav_doc),
         ave_delta_doc = mean(delta_doc),
         sd_delta_doc = sd(delta_doc),
         ave_tdelta_doc = mean(tdelta_doc),
         sd_tdelta_doc = sd(tdelta_doc),
         ave_bge = mean(bge),
         sd_bge = sd(bge)) %>%
  ungroup()
```


```{r}
saveRDS(averages, "~/Desktop/Github/144l_students/Output_data/Week 4/144L_processed_DOC_BGE.rds")
```










